name: Test workflows
run-name: Test docker

on:
  push:
    branches: [main]

jobs:
  test:
    name: Running test workflow
    uses: ./.github/workflows/demo.yaml

  docker:
    name: Test docker
    runs-on: "ubuntu-latest"
    steps:
      - name: Checking out ${{ github.ref }} ${{ github.sha }}
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nodejs-cicd:latest